- README.md
Update readme docs for selectAsset for usage with Promise
Docs were out-of-date
> EXT-1249: Update Readme for selectAsset with Promise

- packages/cli/package.json
Preparing CLI release with Vue 3 fix
> chore: updating version for field-plugin-cli

- packages/cli/src/storyblok/storyblok-client.ts
Now it shows error message and exit with code 1 if the deployment is failed.
The response of the management API is a bit inconsistent.
In a certain case, there is `error` key in the json response.
In a certain case, there is no `error` key, but status code is not 2xx, and there is status text.
So this PR handles them both.
> EXT-1301: show error message if deployment is failed

- package.json
- packages/cli/templates/react/src/App.tsx
- packages/cli/templates/react/src/FieldPluginProvider.tsx
- packages/cli/templates/react/src/components/AssetSelector.tsx
- packages/cli/templates/react/src/components/Counter.tsx
- packages/cli/templates/react/src/components/FieldPlugin.tsx
- packages/cli/templates/react/src/components/ModalToggle.tsx
- packages/cli/templates/react/src/useFieldPlugin.ts
This is the React version of https://github.com/storyblok/field-plugin/pull/123
> EXT-1284: improve useFieldPlugin for react template

- scripts/bump-version.mjs
This PR shows recent commits in `bump-version` script, so that you can better decide the next version.
> EXT-1394: show commits in bump-version script

- packages/cli/src/__tests__/utils.test.ts
- packages/cli/src/commands/deploy.ts
- packages/cli/src/utils.ts
This PR asks for personal access token at `deploy` command if missing. It even offers to save the token in `.env.local` file.
Instead of just quitting the deploy process, it'd be a nicer DX to ask the token (print out the URL to get one)
> EXT-1407: ask for token at deploy command if missing

- package.json
- packages/demo/package.json
- packages/demo/src/components/AssetSelector.tsx
- packages/demo/src/components/ContextRequester.tsx
- packages/demo/src/components/ValueMutator.tsx
- yarn.lock
Small update to demo:
- Upgraded @storyblok/mui version
- Changed button color
> EXT-1472: Update Demo Styles

- packages/field-plugin/tsconfig.json
- packages/field-plugin/tsconfig.node.json
- packages/field-plugin/vite.config.ts
Resolve type error in vite.config.ts when accessing import.meta
> EXT-1473: Vite config type error in import.meta 

- packages/field-plugin/package.json
- yarn.lock
Release `@storyblok/field-plugin@0.0.1-alpha.3`
> chore: release @storyblok/field-plugin@0.0.1-alpha.3

- packages/cli/templates/js/package.json
- packages/cli/templates/react/package.json
- packages/cli/templates/vue2/package.json
- packages/cli/templates/vue3/package.json
- yarn.lock
This PR upgrade templates to use @storyblok/field-plugin@0.0.1-alpha.3
> chore: upgrade templates to use @storyblok/field-plugin@0.0.1-alpha.3

- packages/cli/package.json
This PR releases @storyblok/field-plugin-cli@0.0.1-alpha.9
> chore: release @storyblok/field-plugin-cli@0.0.1-alpha.9

- packages/cli/src/commands/deploy.ts
This PR improves the error message in `deploy` command when bundle is not found.
> EXT-1288: improve error message when bundle is not found

- .github/pull_request_template.md
We're including the issue number as a part of pull-request body.
> chore(common): update pull-request template

- .github/workflows/template-js.yml
- .github/workflows/template-react.yml
- .github/workflows/template-vue2.yml
- .github/workflows/template-vue3.yml
This PR fixes the if conditions in the github workflows.
https://github.com/storyblok/field-plugin/pull/184 had wrong expressions.
Got the info from: https://github.com/orgs/community/discussions/26386#discussioncomment-3251726
> chore(common): fix conditions on the template CIs

- scripts/bump-version.mjs
This PR does two things:
- Even if the working directory is not clean, it lets you continue if you confirm.
- Fix wrong text in the PR description.
> chore(common): improve bump-version script

- packages/container/src/components/App.tsx
- packages/container/vercel.json
This PR changes the path for Sandbox to `/field-plugin`.
JIRA: EXT-1563
> fix(sandbox): use /field-plugin path for Sandbox

- packages/cli/templates/js/README.md
- packages/cli/templates/js/vite.config.ts
- packages/cli/templates/react/README.md
- packages/cli/templates/react/vite.config.ts
- packages/cli/templates/vue2/README.md
- packages/cli/templates/vue2/vite.config.ts
- packages/cli/templates/vue3/README.md
- packages/cli/templates/vue3/vite.config.ts
- packages/field-plugin/src/createFieldPlugin/sandboxUrl.ts
This PR updates the Sandbox URL in the library and the templates.
JIRA: EXT-1564
> fix(common): update Sandbox URL

- .github/workflows/ci-cli.yml
- packages/cli/README.md
- packages/cli/src/commands/add.ts
- packages/cli/src/commands/create/index.ts
- packages/cli/src/commands/create/standalone.ts
- packages/cli/src/commands/create/types.ts
- packages/cli/src/main.ts
- packages/cli/src/utils.ts
This PR renames all the occurrences of "polyrepo" to "standalone" as we think it might be more easy-to-understand.
JIRA: EXT-1800
> fix(cli): rename polyrepo to standalone

- .github/workflows/ci-cli.yml
- packages/cli/templates/vue2/package.json
- packages/cli/templates/vue2/rollup.postbuild.config.js
- packages/cli/templates/vue2/src/App.vue
- packages/cli/templates/vue2/tsconfig.json
- packages/cli/templates/vue2/vite.config.ts
- packages/field-plugin/package.json
- packages/helper-vue2/.gitignore
- packages/helper-vue2/README.md
- packages/helper-vue2/package.json
- packages/helper-vue2/src/FieldPluginProvider.vue
- packages/helper-vue2/src/index.js
- packages/helper-vue2/vite.config.js
- scripts/copy-helpers.sh
- yarn.lock
This adds `@storyblok/field-plugin/vue2` submodule.
Related:
- https://github.com/storyblok/field-plugin/pull/228
- https://github.com/storyblok/field-plugin/pull/224
JIRA: EXT-1828
> feat(helper): add vue 2 submodule

- packages/field-plugin/src/createFieldPlugin/createFieldPlugin.ts
> chore(common): fix formatting error

- README.md
- packages/cli/README.md
- packages/cli/templates/js/README.md
- packages/cli/templates/react/README.md
- packages/cli/templates/vue2/README.md
- packages/cli/templates/vue3/README.md
This PR updates the READMEs. Instead of putting NPM links, I think it's better to redirect to our documentation directly. Also, I've changed some section order, and clarified design system per template.
> docs(common): update README

- CONTRIBUTING.md
This PR adds a section to CONTRIBUTING.md about all-contributors.
JIRA: EXT-2049
> docs(common): update CONTRIBUTING.md

- .github/workflows/template-react.yml
- .github/workflows/template-vue3.yml
- packages/field-plugin/src/index.ts
This PR adds unit tests for templates on CI
JIRA: EXT-2080
> chore(common): run unit tests for templates on CI

- packages/manifest-helper/package.json
- packages/manifest-helper/src/__tests__/manifest.test.ts
- packages/manifest-helper/vite.config.ts
- yarn.lock
Add tests in `@storyblok/manifest-helper` package
Improve the quality and reliability of the package
JIRA: EXT-2012
> test(common): add tests in @storyblok/manifest-helper package

- .github/dependabot.yml
Dependabot is not working, so this PR tries to fix the config.
> chore(common): update dependabot configuration

- .github/dependabot.yml
This PR fixes the typo from the dependabot config.
> fix(common): fix dependabot configuration

- .github/dependabot.yml
This PR changes the dependabot schedule from daily to weekly.
I assigned it to Wednesday (for no reason). Any other day recommendation? :)
> chore(common): update dependabot schedule

- package.json
- packages/cli/package.json
- packages/cli/templates/js/package.json
- packages/cli/templates/monorepo/package.json
- packages/cli/templates/react/package.json
- packages/cli/templates/react/vite.config.ts
- packages/cli/templates/vue2/package.json
- packages/cli/templates/vue3/package.json
- packages/demo/package.json
- packages/field-plugin/package.json
- packages/lib-helpers/react/package.json
- packages/lib-helpers/test/package.json
- packages/lib-helpers/vite/package.json
- packages/lib-helpers/vue3/package.json
- packages/manifest-helper/package.json
- packages/sandbox/package.json
- yarn.lock
This PR upgrades some dependencies and match them to have the same version across the repository.
> chore(common): upgrade dependencies

- CONTRIBUTING.md
Document that the tag needs to be created in the release
> docs(common): include tagging in release steps in CONTRIBUTING.md
