packages/cli/templates/react/tsconfig.json

Set tsconfig.compilerOptions.allowJs to true
To allow for JavaScript by default. It will make it easier for non-TypeScript developers to make the switch to JavaScript
Rename `src/App.tsx` to `src/App.jsx`. Run
```shell
yarn workspace field-plugin-react-template run build     
```

EXT-1246: Set tsconfig.compilerOptions.allowJs to true

---

packages/cli/templates/react/.eslintrc.cjs
packages/cli/templates/react/index.html
packages/cli/templates/react/src/App.tsx
packages/cli/templates/react/src/components/AssetSelector.tsx
packages/cli/templates/react/src/components/Counter.tsx
packages/cli/templates/react/src/components/ModalToggle.tsx
packages/cli/templates/react/src/components/button/Button.tsx
packages/cli/templates/react/src/components/button/button.css
packages/cli/templates/react/src/index.css
packages/cli/templates/react/src/main.tsx
packages/cli/templates/react/src/useFieldPlugin.ts
packages/cli/templates/react/tsconfig.json
packages/cli/templates/react/tsconfig.node.json

Formatted the react starter with
```shell
yarn run prettier --write packages/cli/templates/react
```
Nothing else.
Using our rules in the root of the monorepo. Prettier is still absetn from the react template `package.json`.
For future adjustments, there will be fewer lines changes.

EXT-1247: Format React Starter With Prettier

---

packages/cli/package.json
packages/field-plugin/package.json

For both NPM packages, adding `repository` property to the `package.json` files.
docs: https://docs.npmjs.com/cli/v9/configuring-npm/package-json#repository
We can think of setting the `homepage` property once we have some proper documentation on storyblok.com.
So that the repository is listed on NPM.

EXT-1305: Add repository to package.json

---

packages/cli/src/commands/deploy.ts
packages/cli/src/main.ts

This PR passes `name` option to the `deploy` command correctly.
This was missing before.

EXT-1299: pass name option to deploy command

---

packages/container/src/components/FieldTypePreview.tsx

Removing the Iframe component.
The `Iframe` componen wraps a single box element with `component` set to `"iframe"`. It's simpler to just render the iframe directy in `FieldTypePreview`

EXT-1290: Remove Iframe Component

---

packages/container/src/components/FieldTypePreview.tsx

- Sets the modal height to 80% of the height. 
- Sets the scroll to auto, so that the scroll only appear when the content overflows.
Previously, the modal didn't have a fixed height. If the field plugin wasn't tall, the modal dialog wouldn't cover much of the screen.
Open a field plugin in modal mode and remove most, if not all, elements. With the browser dev tools, set the iframe height to 100px. The window should still cover the 80% of the height.

EXT-1290: Container Modal Height

---

packages/cli/templates/react/.eslintrc.cjs

Disabling ESLint rule react/prop-type in the React template.
React propTypes are nowadays not part of the core React library. Prop types is runtime checking and not needed together with TypeScript.

EXT-1388: Disabling ESLint rule react/prop-type

---

packages/cli/src/commands/deploy.ts
packages/cli/src/storyblok/storyblok-client.ts

This PR fixes the bug that didn't respect `skipPrompts` option at the `deploy` command, and asked for package name.
This PR also fixes a regression that the Update API method threw an error due to a wrong error handling (this part was not deployed yet).

EXT-1300: respect skipPrompts when deciding package name at deploy command

---

packages/cli/src/commands/add.ts
packages/cli/src/commands/create/index.ts
packages/cli/src/commands/create/monorepo.ts
packages/cli/src/commands/deploy.ts
packages/cli/src/main.ts
packages/cli/src/storyblok/storyblok-client.ts
packages/cli/src/utils.ts
scripts/bump-version.mjs

This PR enables support for both endpoints.
- https://mapi.storyblok.com/v1/partner_field_types/
- https://mapi.storyblok.com/v1/field_types/
It adds a new option `--scope` to the `deploy` command. It is prompted if not given.
---
This PR is a bit easier to review if you ignore whitespace changes.

EXT-1087: support different endpoints

---

packages/cli/templates/vue3/src/components/FieldPluginProvider.vue
packages/cli/templates/vue3/src/utils/convertToRaw.ts
packages/cli/templates/vue3/src/utils/index.ts

This PR convert value to raw object that is being passed to setValue in vue 3 template.
In Vue, Proxy is wildly used for its reactivity. And it’s a common case where user passes something reactive to setValue() method of Field Plugin library. Then postMessage fails because it cannot serialize the Proxy instance. So it’s necessary to un-proxy that object.
Also, we need to unref refs. Otherwise we will have unnecessary object instead of a simple value.
I changed `Counter` component to use both `ref` and `reactive` and confirmed that the value was correctly converted to a raw object.

EXT-1387: convert value to raw object for setValue in vue 3 template

---

package.json
packages/cli/src/commands/add.ts

When there is a new package added (either as a polyrepo, or to a monorepo), now `add` command suggests user to deploy that initial version.
If user deploys the field plugin right away, they will have the correct URL on the Storyblok side to test the field plugin. Also, it's always nice to have things set up in advance, rather than sweating with deployment after all the work.
Initially I was going to run the `deploy` command within `add` command directly, but it's maybe better to loosely display which command to run to deploy the field plugin. It might overwhelm users in the first place, even making a decision whether or not they want to deploy it right now.

EXT-1293: `add` command suggests `deploy` command

---

packages/container/package.json
packages/container/src/components/App.tsx
packages/container/src/components/FieldPluginContainer.tsx
yarn.lock

The Sandbox's URL persists the origin value in the URL query parameters.
In this way, it is possible to share a field plugin with a single URL. For example, to share the preview deployement of the Bynder field plugin, open 
https://storyblok-field-plugin-sandbox.vercel.app?origin=https://storyblok-bynder.vercel.app
The example aboe won't work until this pull request is merged to main. See the next section.
Open the preview deployment from this pull request. Paste `https://storyblok-bynder.vercel.app/` into the origin input field. Notice how the URL change.

EXT-1445: Persist Sandbox Origin in URL Query

---

packages/container/src/components/FieldTypePreview.tsx

Fix the attributes on the iframe element. From spreading all `props` into the attributes to only setting the `src`.
This would generate an error message, stating that the iframe element does not have an attribute called `isModal`.

EXT-1464: Clear Console from Errors

---

packages/cli/templates/js/src/main.js
packages/cli/templates/react/src/main.tsx
packages/cli/templates/vue2/src/main.ts
packages/cli/templates/vue3/src/main.ts

Nicer error message from failing `fieldtype-wrapper.js`.
Replaces the uncaught error from https://github.com/storyblok/field-plugin/issues/107
with
When a client upload code to the field plugin editor, Storyblok will serve a document with a script that contains that code. But the content of the script element will not be exactly the code that the client uploaded; it will be appended with a code snippet from Storyblok. For example, the if the client uploads
```javascript
console.log('hello')
``` 
Storyblok will serve a document with
```html
<script type="text/javascript">
console.log('hello')
var customComp = window.Storyblok.vue.extend(window.storyblok.field_types['sb-dummy'])
window.Storyblok.vue.component('custom-plugin', customComp)
window.StoryblokPluginRegistered = true
</script>
``` …

EXT-1403-nicer-error-message-to-replace-the-one-from-the-failing-fieldtype-wrapper-js

---

packages/container/src/components/FieldPluginContainer.tsx
packages/container/src/components/FieldTypePreview.tsx
packages/container/src/dom/createContainerMessageListener.ts

Let the user type in any URL. Before, the app would error if the provided value was not an origin (i.e. no path or query parameters were allowed).
The Sandbox now also displays a nicer error  message when the URL is invalid. There are three scenarios:
The URL points to a field plugin:
The URL is valid, but points to a URL where there is no field plugin hosted:
The URL is invalid:
The container compared the origin of the message with the value that the user specified in the container's "Origin" field.
Because URLs with trailing slashes are not valid origins, the message origin from the field plugin would not match the value that the user specified in the conrtainer, causing the container to ignore all message. For example,`http://localhost:8080/` and `http://localhost:8080/base-url` would …

EXT-1451: Allow any URL for Previewed Field Plugins  

---

packages/field-plugin/src/createFieldPlugin/createAutoResizer.test.ts
packages/field-plugin/src/messaging/pluginMessage/containerToPluginMessage/AssetSelectedMessage.test.ts
packages/field-plugin/src/messaging/pluginMessage/containerToPluginMessage/FieldPluginSchema.test.ts
packages/field-plugin/src/messaging/pluginMessage/containerToPluginMessage/MessageToPlugin.test.ts
packages/field-plugin/src/messaging/pluginMessage/containerToPluginMessage/StateChangedMessage.test.ts
packages/field-plugin/src/messaging/pluginMessage/containerToPluginMessage/StoryData.test.ts
packages/field-plugin/src/messaging/pluginMessage/pluginToContainerMessage/AssetModalChangeMessage.test.ts
packages/field-plugin/src/messaging/pluginMessage/pluginToContainerMessage/GetContextMessage.test.ts
packages/field-plugin/src/messaging/pluginMessage/pluginToContainerMessage/HeightChangeMessage.test.ts
packages/field-plugin/src/messaging/pluginMessage/pluginToContainerMessage/MessageToContainer.test.ts
packages/field-plugin/src/messaging/pluginMessage/pluginToContainerMessage/ModalChangeMessage.test.ts
packages/field-plugin/src/messaging/pluginMessage/pluginToContainerMessage/PluginLoadedMessage.test.ts
packages/field-plugin/src/messaging/pluginMessage/pluginToContainerMessage/ValueChangeMessage.test.ts
packages/field-plugin/src/utils/hasKey/hasKey.test.ts

In the tests for the library, replace 
- `toBeTruthy` with `toEqual(true)`
- `toBeFalsy` with `toEqual(false)`
To not fall victim of type coercion. These functions should all return boolean values.
```
yarn workspace @storyblok/field-plugin test
```

EXT-1476: Replace toBeTruthy and toBeFalsy with equality check

---

scripts/bump-version.mjs

This PR fixes `bump-version` script.
It uses `npm version` command to update the `version` in `package.json` file, but it fails with this error message.
```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eunjae/.npm/_logs/2023-04-27T07_55_00_345Z-debug-0.log
Error: npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eunjae/.npm/_logs/2023-04-27T07_55_00_345Z-debug-0.log
at file:///Users/eunjae/workspace/field-plugin/scripts/bump-version.mjs:163:8
exit code: 1
```
We have some dependencies like:
```
"@storyblok/field-plugin": "workspace:*"
```
I think it's better …

chore: fix bump-version script

---

packages/cli/src/commands/create/index.ts
packages/cli/src/commands/deploy.ts
packages/cli/src/main.ts
packages/cli/src/utils.ts

This PR clarifies `--dir` and `--output` options in deploy command.

EXT-1130: clarify --dir and --output options in deploy command

---

packages/container/src/components/FieldPluginContainer.tsx
packages/container/src/components/ValueView.tsx

Added a button that lets the user reset the field plugin value. The initial value is `undefined`.
Extracted new component for displaying the value: ValueView.tsx. The same will be done for the other views (isModal, story, etc).
This is not a big problem right now, because the value does not persist in between page reloads. But once we implement localStorage for the field plugin value, it will be necessary to have this functionality.
Notice how frustrating the field plugin editor in app.storyblok.com can be because it's not possible to reset the value to `undefined`. Developers need to hack their existing plugin, load a new plugin with the sole purpose of resetting the value, or use the MAPI.
Load a plugin in the preview deployment, set the value to something, and then click on the button.

EXT-1453: Reset Value Button

---

packages/container/src/components/FieldPluginContainer.tsx

When the developer change the state in the container, the new state is sent to the field plugin.
In the example, notice how the text on the button changes in real-time:
When the user would change the options, they would have to manually refresh the plugin.

EXT-1481: Sync Data When Changed in the Container

---

package.json
packages/container/package.json
yarn.lock

This cleans up some devDependencies.
In `packages/container/package.json`, I've made this change:
```diff
-    "@storyblok/field-plugin": "workspace:*",
+    "@storyblok/field-plugin": "0.0.1-alpha.2",
```
According to @johannes-lindgren , `container` package barely uses this library, and it should continuously work with newly created field plugins with latest version of the library. So it'd be better for us to pin a certain version here instead of specifying the workspace version.
We can update this version when we move to beta and also when we move to stable.

chore: pin the library version in Sandbox

---

packages/cli/src/__tests__/utils.test.ts
packages/cli/src/commands/add.ts
packages/cli/src/utils.ts

- show relative path to use if the directory when field plugin was created is a subdirectory
[EXT-1302](https://storyblok.atlassian.net/browse/EXT-1302)
1. Create a field plugin outside the current directory
2. Create a field plugin inside the current directory
[EXT-1302]: https://storyblok.atlassian.net/browse/EXT-1302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EXT-1302: show shorter path for created repository

---

.github/workflows/npm-publish-library.yml
.github/workflows/template-js.yml
.github/workflows/template-react.yml
.github/workflows/template-vue2.yml
.github/workflows/template-vue3.yml

Currently we run CI tasks for templates only when their own code changes. However, whenever something changes on the library side, we need to run the tests compatibility with the templates.

chore: run CI tasks for templates when the library code changes

---

packages/cli/src/utils.ts

This PR stops the CLI from running `git init` if the directory already belongs to a git repository.

EXT-1338: do not initialize repo if already

---

packages/cli/package.json

This PR excludes `node_modules/` and `dist/` folders of templates from the CLI npm distribution.
Our distribution is unnecessarily bloated.

chore: exclude node_modules/ and dist/ from CLI npm distribution

---

.github/workflows/pr-title.yml
scripts/bump-version.mjs

This PR updates pull-request title checking logic.
Now it's following the semantic rules: https://github.com/amannn/action-semantic-pull-request
EXT-1255
It helps us better distinguish commits by type of work and package.
Current I've put the following scopes:
- common
- lib
- sandbox
- cli
- cli-create
- cli-add
- cli-deploy
Any update you'd like to see?
(They are used like `fix(cli-deploy): load environment variables from .env.local`)

chore(common): update pull-request title checking logic

---

scripts/bump-version.mjs

bump-version.mjs now checks if there are any new, uncommitted files before it proceeds.
`git diff-index --quiet HEAD --` doesn't detect _new_ files.
Ansure that the are no uncmitted change, add a new file, and run
```shell
echo $?
git diff-index --quiet HEAD --
echo $?
git add .
git diff-index --quiet HEAD --
echo $?
```
The first and second echo commands will give `0`, while the last will give `1`.

EXT-1495: check-version script to Detect new Files

---

.prettierignore

This PR removes templates from the `.prettierignore`, which was introduced in #152 
Since #152, when we work on the templates, the "format-on-save" didn't work at all on VSCode.
We shouldn't exclude the source files from prettier.

chore: revert prettier config for templates

---

packages/cli/templates/js/vite.config.js
packages/cli/templates/react/vite.config.ts
packages/cli/templates/vue2/vite.config.ts
packages/cli/templates/vue3/vite.config.ts

For all templates, configuring rollup to output in CommonJs. 
EXT-1501
The document that Storyblok serves for field plugins wraps the code within a script element. This element does not have the attribute `type` set to `"module"`. Thus, if one provides code that uses JavaScript modules, this will fail with a syntax error. 
However, during development, Vite utilizes JavaScript modules and serves the code from a script element with `type="module"`. This descrepency could make the developer think that their code is functional, while after deploying to production, it would fail to execute.

fix(template): Compile templates to CommonJS

---

packages/container/src/components/FieldPluginContainer.tsx

Changed the initial/default content (`data.value`) to be an empty string.
JIRA: EXT-1500
This is the default behaviour of the Visual Editor.

fix(sandbox): Initial Content Changed to an Empty String (`""`)

---

packages/container/src/components/FieldPluginContainer.tsx

Extracts the logic inside `FieldPluginContainer` into a hook `useSandbox`.
JIRA: EXT-1534
Easier to read the code.
Should work as before. See the preview deployment of the sandbox.

refactor(sandbox): Exctract `FieldPluginContainer` logic into a hook.

---

packages/field-plugin/src/createFieldPlugin/FieldPluginActions.ts
packages/field-plugin/src/createFieldPlugin/createFieldPlugin.ts
packages/field-plugin/src/createFieldPlugin/createPluginActions/createPluginActions.test.ts
packages/field-plugin/src/createFieldPlugin/createPluginActions/createPluginActions.ts

Removes `setPluginReady` from `FieldPluginActions`.
`setPluginReady` is only used internally in `createFieldPlugin` to request the initial state from the Visual Editor (container)

feat(lib)!: `setPluginReady` Removed from `FieldPluginActions`

---

README.md
package.json
packages/container/package.json
packages/container/src/components/ContentView.tsx
packages/container/src/components/FieldPluginContainer.tsx
packages/container/src/dom/createContainerMessageListener.ts
packages/field-plugin/src/createFieldPlugin/FieldPluginActions.ts
packages/field-plugin/src/createFieldPlugin/FieldPluginData.ts
packages/field-plugin/src/createFieldPlugin/createPluginActions/createPluginActions.test.ts
packages/field-plugin/src/createFieldPlugin/createPluginActions/createPluginActions.ts
packages/field-plugin/src/createFieldPlugin/createPluginActions/partialPluginStateFromStateChangeMessage.ts
yarn.lock

BREAKING CHANGES:
- `setHeight` removed from `FieldPluginActions`.
- `height` removed from `FieldPluginData`.
Non-breaking changes:
- The sandbox was refactored to use the terminology `content` instead of `value`
- The sandbox removed the height from the `FieldPluginResponse.data` view.
- The sandbox changed the name of `isModalOpen` from incorrect `isModal` from the `FieldPluginResponse.data` view.
- Upgrading to Typescript v5 so that we can use `satisfies` in the container
Because the automatic resizing will call setHeight, the developer will not be in control of the height. But if we expose it via FieldPluginActions, we’re leading the API consumers to believe that they can influence the height. Any such usage of setHeight would interfere with the automatic resizing. 
If we remove it …

feat(lib)!: `setHeight` removed from `FieldPluginActions`. `height` removed from `FieldPluginData`.

---

packages/container/src/components/FieldPluginContainer.tsx
packages/container/src/components/usePluginParams.tsx

When selecting an asset, the sandbox will respond with an image that is served from the URL where the sandbox is hosted.
JIRA: EXT-1478
To make the sandbox's asset selector work when deployed. Previously, `http://localhost:7070` was hard coded.
Try the Vercel preview

feat(sandbox): Reading sandbox origin from `window.location`

---

scripts/bump-version.mjs

`yarn bump-version` command now automatically fills the pull request body with minimal text.
Release pull-requests normally don't need any information in its body.

chore(common): update bump-version script

---

.github/workflows/check-if-releasing-library.yml
.github/workflows/template-js.yml
.github/workflows/template-react.yml
.github/workflows/template-vue2.yml
.github/workflows/template-vue3.yml

This PR fixes the wrong implementation of https://github.com/storyblok/field-plugin/pull/184
Template CI tasks run on `push` trigger: https://github.com/storyblok/field-plugin/blob/658f5454ca9f93b9e680ad86a61c355371253212/.github/workflows/template-vue3.yml#L2-L3
In that context, we don't have access to `github.event.pull_request`. It exists only on `pull_request` trigger.
So in this PR, I've added `check-if-releasing-library.yml` which uses `jwalton/gh-find-current-pr@v1` action to retrieve the pull-request title and validates it.
And all the other `template-*.yml` workflows depend on this check file and uses its result.
https://docs.github.com/en/actions/using-workflows/reusing-workflows

chore(common): fix workflows to check pull-request title correctly

---

packages/container/src/components/FieldPluginContainer.tsx
packages/container/src/components/FieldTypePreview.tsx
packages/container/src/components/usePluginParams.tsx

Fixes the _reload plugin_ button.
The way we refreshed the iframe window was by utilizing a trick from React. By setting the `key` on the react element and thereafter changing it, we force React to insert a new iframe element into the document.
The key that we used was a random string that we would regenerate on a function call. We called this calue a "uid". But in previous refactoring, the key was accidentally mixed up with the uid from the `pluginParams` object, which we never update. Thus, the functionality was broken.
We avoid this problem from happening again by removing the key property from the iframe. Instead, we will force a refresh of the iframe window by changing the URL. We do this by updating the `uid` in the query parameters, which we find in the `pluginParams` object.
JIRA: …

fix(sandbox): broken reload plugin button

---

packages/demo/src/components/FieldPluginDemo.tsx
packages/demo/src/components/UpdaterFunctionDemo.tsx
packages/field-plugin/src/createFieldPlugin/FieldPluginActions.ts
packages/field-plugin/src/createFieldPlugin/createPluginActions/createPluginActions.ts

Issue: EXT-1558
`setContent`  and `setModalOpen` now accept updater functions as arguments.
In React and other frameworks with batched updates, unless you update a state with an updater function, multiple calls to `setState` will result in only a single update, because the latter updates overwrite the previous ones.
The same thing can happen in a field plugin with `setContent` and `setModalOpen`.
Run the demo and try out the new button "IncrementTwice".
(The background is being fixed in #205)

feat(lib): updater functions

---

.github/workflows/pr-title.yml
packages/demo/src/components/AssetSelector.tsx
packages/demo/src/components/ContextRequester.tsx
packages/demo/src/components/FieldPluginDemo.tsx
packages/demo/src/components/ModalToggle.tsx
packages/demo/src/components/ValueMutator.tsx

Updated styles for the demo app:
- white background with padding and a grey border
- headers and dividers are separated
Also adding a new scope `demo` to the pull request title check.
The background was transparent, so the grey background in the Sandbox/Visual Editor made it hard to read.
Run locally

fix(demo): updated styles

---

README.md
packages/cli/README.md
packages/cli/templates/js/package.json
packages/cli/templates/monorepo/package.json
packages/cli/templates/react/package.json
packages/cli/templates/vue2/package.json
packages/cli/templates/vue3/package.json

use `@beta` instead of `@alpha` with the cli 
Users are currently misled to use the alpha version

fix(common): use @beta instead of @alpha with the cli 

---

packages/cli/templates/react/README.md
packages/cli/templates/react/src/App.tsx
packages/cli/templates/react/src/components/FieldPlugin.tsx
packages/cli/templates/vue2/README.md
packages/cli/templates/vue2/src/App.vue
packages/cli/templates/vue2/src/components/FieldPlugin.vue
packages/cli/templates/vue3/README.md
packages/cli/templates/vue3/src/App.vue
packages/cli/templates/vue3/src/components/FieldPlugin.vue

Continuing on #211, this PR provides an empty `<FieldPlugin />` component so that users can easily replace the example component with it.

chore(template): provide empty component as placeholder

---

packages/cli/templates/vue2/src/components/FieldPluginProvider.vue

Issue: EXT-1728
Use scoped styles for `FieldPluginProvider.vue`.
The templates use global styles which cause issues.
This one is caused when you remove the `/*Layout Styles*/` section in style.css. Because the `FieldPluginProvider.vue` has a div element at the root that uses the global style `w-full`,when you remove the layout styles, the app will not take up the full width.
The Vue 3 template does not have this excact issue, because in Vue 3, it is allowed to not have an element at the root.

fix(template): use scoped styles for FieldPluginProvider.vue

---

packages/container/src/components/FieldPluginContainer.tsx
packages/demo/src/components/FieldPluginDemo.tsx
packages/demo/src/components/LanguageView.tsx
packages/field-plugin/src/createFieldPlugin/FieldPluginData.ts
packages/field-plugin/src/createFieldPlugin/createPluginActions/createPluginActions.ts
packages/field-plugin/src/createFieldPlugin/createPluginActions/partialPluginStateFromStateChangeMessage.ts
packages/field-plugin/src/messaging/pluginMessage/containerToPluginMessage/StateChangedMessage.test.ts
packages/field-plugin/src/messaging/pluginMessage/containerToPluginMessage/StateChangedMessage.ts
packages/field-plugin/src/messaging/pluginMessage/containerToPluginMessage/StoryData.test.ts
packages/field-plugin/src/messaging/pluginMessage/containerToPluginMessage/StoryData.ts

1. library: added storyLang and removed lang property from the story object
2. demo: added UI to display the language parameter
3. container: removed the hardcoded lang property
Removed lang parameter from story object and added the language as storyLang to the root object. 
JIRA: [EXT-1801](https://storyblok.atlassian.net/browse/EXT-1801)
After looking into the get-context message delivered to the plugin, the team has found out that the story response does not include the lang property. This was the motivation to bring the language property back as it is passed via the loaded event. To make it more clear the decision was made to call it storyLang as the language is coherent with the language of the story and not the storyblok interface.
1. Build field plugin demo
4. Open the field plugin …

feat(common): field plugin sdk data story language is missing in some cases

---

.github/workflows/npm-publish-cli.yml

People forget `@latest` when running npx `@storyblok/field-plugin-cli`, and they end up getting an old version of the CLI.
We can use `npm dist-tag` command to keep `@beta` and `@latest` the same.
ref: https://www.grzegorowski.com/what-are-npm-dist-tags-how-to-use-them
JIRA: EXT-1805

chore(cli): keep latest tag on npm up to date

---

.github/workflows/ci-cli.yml
packages/cli/README.md
packages/cli/bin.js
packages/cli/src/commands/add.ts
packages/cli/src/commands/create/index.ts
packages/cli/src/commands/create/monorepo.ts
packages/cli/src/commands/create/polyrepo.ts
packages/cli/src/commands/create/types.ts
packages/cli/src/commands/types.ts
packages/cli/src/main.ts
packages/cli/src/utils.ts
packages/cli/templates/js/README.md
packages/cli/templates/js/vite.config.ts
packages/cli/templates/monorepo/package.json
packages/cli/templates/react/README.md
packages/cli/templates/react/vite.config.ts
packages/cli/templates/vue2/README.md
packages/cli/templates/vue2/vite.config.ts
packages/cli/templates/vue3/README.md
packages/cli/templates/vue3/vite.config.ts

This PR adds support for npm and pnpm.
* It adds `--packageManager` option to `create` and `add` command.
* In case of monorepo with yarn, it adds `"packageManager": "yarn@3.2.4"` to `package.json`.
* In case of monorepo with pnpm,
* it adds `"packageManager": "pnpm"` to `package.json`.
* it adds `pnpm-workspace.yaml` file as well.
JIRA: EXT-1063
We initially started this project with yarn and yarn workspace. However, we'd like to support those using npm and pnpm. And both of them support workspaces.

feat(cli): support different package managers

---

packages/helper-vue3/src/FieldPluginProvider.vue

This PR removes properties that no longer exist in `FieldPluginProvider` of the vue 3 template.
JIRA: EXT-1817
The Jira ticket mentions the changing `options`, but actually the same problem happened to `plugin.data.content` too.

fix(template): remove non-existing properties correctly in vue 3 template

---

packages/cli/src/commands/create/monorepo.ts

This PR removes unnecessary `npm install`, `yarn install`, or `pnpm install` during the monorepo creation process, because the install command is called right after adding an actual field plugin package.
It also provides a link to doc regarding monorepo.
JIRA: EXT-1818

fix(cli): remove unnecessary install command in monorepo and provide docs

---

packages/cli/src/commands/deploy.ts
packages/cli/src/main.ts
packages/cli/src/storyblok/storyblok-client.ts

Since past 2 weeks a new feature has been added to the product where organizations are able to create their own field plugins. For this new feature a new API endpoint has been added so we need to consider it inside our CLI to give the user the option to deploy to an organisation. 
[JIRA: EXT-1849](https://storyblok.atlassian.net/browse/EXT-1849)

feat(cli): deploy command including org scope

---

.github/dependabot.yml
.github/workflows/pr-title.yml

`dependabot` created #250, which includes major version updates. So this PR
- re-configure dependabot only to upgrade minor and patch versions
- and include `deps` as a PR title scope like `chore(deps)`

chore(common): update dependabot configuration

---

packages/field-plugin/src/createFieldPlugin/FieldPluginActions.ts
packages/field-plugin/src/createFieldPlugin/FieldPluginData.ts
packages/field-plugin/src/createFieldPlugin/FieldPluginResponse.ts
packages/field-plugin/src/createFieldPlugin/createFieldPlugin.ts
packages/field-plugin/src/createFieldPlugin/createPluginActions/createPluginActions.test.ts
packages/field-plugin/src/createFieldPlugin/createPluginActions/createPluginActions.ts
packages/field-plugin/src/createFieldPlugin/createPluginActions/partialPluginStateFromStateChangeMessage.ts

This PR adds `parseContent` as the option to `createFieldPlugin()` function. This makes sure that we always pass around correctly formed payload.
This is almost the exact porting of #241. @johannes-lindgren did the job there, but since #260, it was too hard to resolve conflicts. So I've created a new PR here.
JIRA: EXT-1918
more discussion on #241 
It's expected to see tests broken in this pull request, as the demo and the helpers are not taking this change into account. It will be fixed in the separate pull request.

feat(lib): add parseContent

---

.github/dependabot.yml
packages/cli/templates/monorepo/package.json
yarn.lock

We have configured dependabot but it's not working.
https://github.com/storyblok/field-plugin/network/updates/722059282
In the end of the log I've found something suspicious:
```
updater | +-----------------------------------+
updater | |   Dependencies failed to update   |
updater | +-------------------+---------------+
updater | | eslint-plugin-vue | unknown_error |
updater | +-------------------+---------------+
```
Not sure what's going on, but let's exclude `eslint-plugin-vue` from our dependabot config, and see what happens.

chore(common): fix dependabot error

---

packages/cli/templates/js/src/style.css
packages/cli/templates/react/src/components/FieldPluginExample/example.css
packages/cli/templates/react/src/style.css
packages/cli/templates/vue2/src/components/FieldPluginExample/example.css
packages/cli/templates/vue2/src/style.css
packages/cli/templates/vue3/src/components/FieldPluginExample/example.css
packages/cli/templates/vue3/src/style.css

Resizing of the field plugin UI inside the iFrame has changed and been release in the previous sprint. 
Now once the plugin is loaded it sends a property to the Storyblok App --> `modalFullHeight: true`.
This property signals to the Container that in case the modal is open, the iframe should add `size=auto` inside the inline styles.
By adding this option, it should be easier for the user to create sticky headers and footers. Before there have been issues where such designs were not easily possible. This PR adds some styles to enable this feature. 
In the following video, I demonstrate the new possible implementation. The div with green background is sticky to top. The red div is sticky to bottom. 
https://www.loom.com/share/5cc5211c2ec6491c887ec1b78ad82336
[JIRA: …

fix(template): adapting to the new way resizing of the field plugin is handled

---

packages/cli/src/utils.ts

**Scope of the PR:**
- _Adding a new check_ to resolve an issue in case a an env variable is set inside GitHub action like this: 
```
- name: Deploy
env:
STORYBLOK_PERSONAL_ACCESS_TOKEN: ${{secrets.STORYBLOK_PERSONAL_ACCESS_TOKEN}}
run: yarn workspace commerce-layer deploy --skipPrompts
```
- _Refactoring_ `getPersonalAccessToken()` function to make it more clear and readable.
TODO: 
You can find a more detailed description inside JIRA: [EXT-2013](https://storyblok.atlassian.net/browse/EXT-2013)
[EXT-2013]: https://storyblok.atlassian.net/browse/EXT-2013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(cli): add logic to handle a case where CI is setting an env variable

---

packages/cli/src/__tests__/utils.test.ts
packages/cli/templates/js/src/main.js
packages/cli/templates/react/src/components/FieldPlugin.tsx
packages/cli/templates/react/src/components/FieldPluginExample/index.tsx
packages/cli/templates/vue2/src/fieldPlugin.js
packages/cli/templates/vue3/src/components/FieldPlugin.vue
packages/cli/templates/vue3/src/components/FieldPluginExample/index.vue
packages/demo/src/components/FieldPluginDemo.tsx
packages/field-plugin/helpers/react/src/useFieldPlugin.ts
packages/field-plugin/helpers/vue3/src/useFieldPlugin.ts
packages/field-plugin/src/createFieldPlugin/createFieldPlugin.ts
packages/field-plugin/src/createFieldPlugin/createPluginActions/createPluginActions.test.ts
packages/field-plugin/src/createFieldPlugin/createPluginActions/createPluginActions.ts
packages/field-plugin/src/createFieldPlugin/createPluginActions/partialPluginStateFromStateChangeMessage.ts

This PR adds `validateContent` to `createFieldPlugin()` function as a parameter.
- renamed from `parseContent`
- returns validation result (error if invalid)
- optional now (used to be required)
- prints out a warning message if the content is invalid
While we don't have a way on the Visual Editor to prevent from saving invalid custom field plugin data, this pull request is the first step towards it by letting people define their validation logic.
This `validateContent` enables users to
1. send valid / invalid status and the error message to the Visual Editor
2. bring better type-safety
The Visual Editor will later use (1) to properly display the error message and prevent from saving invalid data.
(2) was still here since `parseContent`, to be clear.
Also, we're making `validateContent` …

feat(lib): add validateContent (renamed from parseContent)

---

packages/cli/config.ts
packages/cli/vite.config.ts

This PR replaces `__dirname` with something else.
I ran `yarn bump-version`, but got this error:
```
➜ yarn bump-version
/Users/eunjae/workspace/field-plugin/packages/cli/config.ts:38
export const TEMPLATES_PATH = resolve(__dirname, 'templates')
^
ReferenceError: __dirname is not defined in ES module scope
at <anonymous> (/Users/eunjae/workspace/field-plugin/packages/cli/config.ts:38:39)
at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
Node.js v18.16.0
```
I'm not sure if I understand this issue 100% exactly. From my understanding, our library and the CLI gets transpiled to CJS. So using `__dirname` doesn't cause any problem.
However, when running `bump-version.ts`, it's run in ESM scope. And `__dirname` doesn't exist there. To work around this issue, we're not using …

fix(cli): replace __dirname

---

packages/field-plugin/helpers/vite/package.json
packages/field-plugin/helpers/vite/src/utils/text.ts
packages/field-plugin/helpers/vite/vite.config.ts
scripts/dev-template.mjs
yarn.lock

```
npx @storyblok/field-plugin-cli@rc
```
After creating a monorepo, I ran yarn workspace <package-name> dev and got this error message:
```
failed to load config from /Users/eunjae/sandbox/ext-1971/t1/packages/p1/vite.config.ts
error when starting dev server:
file:///Users/eunjae/sandbox/ext-1971/t1/node_modules/@storyblok/field-plugin/dist/vite/index.js:2
import { Chalk } from "chalk";
^^^^^
SyntaxError: Named export 'Chalk' not found. The requested module 'chalk' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
import pkg from 'chalk';
const { Chalk } = pkg;
at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
at async ModuleJob.run …
```

fix(cli): replace chalk with kleur

---

packages/cli/README.md
packages/cli/src/commands/__tests__/add.test.ts
packages/cli/templates/js/package.json
packages/cli/templates/react/package.json
packages/cli/templates/vue2/package.json
packages/cli/templates/vue3/package.json

Update the CLI version from beta to rc in all field plugin templates.
JIRA: EXT-2042
This will allow the manifest deployment to work for new plugins when calling the deploy script located in the respective package.json files.

fix(template): Update the CLI version used by the templates

---

packages/cli/templates/js/README.md
packages/cli/templates/react/README.md
packages/cli/templates/vue2/README.md
packages/cli/templates/vue3/README.md

Add details about the manifest file setup inside our templates.
JIRA: EXT-1881

docs(template): add documentation on manifest file

---

.all-contributorsrc
README.md

This PR sets up [all-contributors](https://allcontributors.org) to recognize all the contributors to this repository.
Once this is set up, you can use it like [this](https://allcontributors.org/docs/en/bot/usage).
(Types of contributions supported: https://allcontributors.org/docs/en/emoji-key#table)

chore(common): setup all-contributors

---

packages/cli/templates/js/field-plugin.config.json
packages/cli/templates/react/field-plugin.config.json
packages/cli/templates/vue2/field-plugin.config.json
packages/cli/templates/vue3/field-plugin.config.json

This PR fixes the indentation of manifest files (from 4 spaces to 2 spaces, according to the overall configuration in this repository)

chore(template): fix indentation of manifest files

---

scripts/prepare-dev-vite-configs.mjs

After facing some issues when bumping versions, where .DS_store files were copied, this logic should restrict to receive only the template directories for copying. 
[JIRA: EXT-2102](https://storyblok.atlassian.net/browse/EXT-2102)

fix(common): add logic to restrict receiving only template directories

---

packages/cli/src/commands/create/__tests__/monorepo.test.ts
packages/cli/src/commands/create/monorepo.ts

* Set specific version for pnpm in packageManager field in the package.json file when creating monorepos
* Exclude yarn specific files from monorepos that do not use yarn
fixes #329 
* pnpm monorepo creation failed when pnpm is installed using Corepack. This issue was caused by the missing version of the packageManager in the package.json file
* Even if the monorepo was created with a package manager other than yarn the yarn specific config files were copied to the target folder.
I validated the corepack fix on my machine and tested monorepo creation with all package managers.
I expanded the test for monorepo creation to validate the yarn config file changes.

fix(cli): set specific version of pnpm for monorepos

---

packages/field-plugin/src/createFieldPlugin/createFieldPlugin.ts
packages/field-plugin/src/createFieldPlugin/createPluginActions/createPluginMessageListener/createPluginMessageListener.ts

This PR uses correct `origin` for postMessage.
JIRA: EXT-2133
Everything should work the same.

fix(lib): use origin for postMessage strictly

---

packages/cli/src/commands/deploy/helper.ts

Improve the printed messages regarding options found in a manifest file and add a disclaimer on what to expect about the behavior of these options when the plugin gets attached to a Field.
It can be common for users to think that the option values (found in a manifest file) will be shared with a real Field when the plugin gets attached to it, but, it isn't the way it happens. 
To avoid sensitive data from getting leaked with other users, all the option values reside accessible only during development time (through the Field Plugin Editor or the Sandbox), and as soon as the field plugin gets attached to a real Field, only the option names are fetched and listed to the user to fulfill.
JIRA: EXT-2170
Creation with no options:
Creation with options:
Update with no options:
Update with …

feat(cli): add a disclaimer on how the manifest options will behave when published

---

scripts/bump-version.ts

It fetches the latest version tag before proceeding with the versioning bumping.
If the developer doesn't have the latest tag locally, the script will fail to revise it. So, fetching it before will prevent it from happening.
**Result**:
JIRA: EXT-2180

chore(common): fetch the latest version tag when bumping the version

---

package.json
packages/field-plugin/helpers/test/src/index.ts

This PR resolves CI breaking after PR #333 was merged. This error occurred because the origin inside the vitest environment was 'localhost' which is currently not permitted.
[JIRA: EXT-2188](https://storyblok.atlassian.net/browse/EXT-2188)
1. Inside the root run `yarn test:react` and `yarn test:vue3`

fix(helper): test setup mimics sandbox environment

---

.github/dependabot.yml

This fixes the wrong dependabot configuration.
[The doc](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem) says `yarn` is supported, but it actually [failed](https://github.com/storyblok/field-plugin/runs/21559520157).

chore(common): fix dependabot configuration

---

packages/field-plugin/helpers/test/src/index.ts
packages/field-plugin/src/createFieldPlugin/FieldPluginData.ts
packages/field-plugin/src/createFieldPlugin/createPluginActions/createPluginActions.test.ts
packages/field-plugin/src/createFieldPlugin/createPluginActions/createPluginMessageListener/handlePluginMessage.test.ts
packages/field-plugin/src/createFieldPlugin/createPluginActions/partialPluginStateFromStateChangeMessage.ts
packages/field-plugin/src/messaging/pluginMessage/containerToPluginMessage/FieldPluginSchema.test.ts
packages/field-plugin/src/messaging/pluginMessage/containerToPluginMessage/FieldPluginSchema.ts
packages/field-plugin/src/messaging/pluginMessage/containerToPluginMessage/LoadedMessage.test.ts

Added new property to the plugin.data object called `translatable`. This is a field setting that can be adjusted by the content editor and came in as a feature request from a customer. 
In order to make the local development easier, sandbox was extended with a checkbox 'Translatable' where the user can manipulate the new property accordingly.
You can review the Documentation updated [here](https://app.storyblok.com/#/me/spaces/88751/stories/0/0/314827086).
[JIRA: EXT-2225](https://storyblok.atlassian.net/browse/EXT-2225)

fix(lib): add translatable as part of the plugin payload

---

packages/cli/src/commands/deploy/helper.ts
packages/cli/src/storyblok/storyblok-client.ts

It allows our CLI to handle duplicated name errors when deploying new field plugins.
JIRA: EXT-2053
As we don't have an ENDPOINT to check globally (from all users and scopes) whether a plugin with the same name, already exists in someone's account or in a different scope, naming collisions can happen during creation time.
The idea then is to not check it before trying to create a new plugin (because we don't have an endpoint for doing it globally) but a failing first approach, meaning that if we are not sure if a plugin with the same name exists or not we first try to create it and if it fails due `name collision` error, we prompt the user to rename it and try again with the new name. The user is going to be prompted about providing a new name until a unique name is provided or he/she …

feat(cli): check for duplicated names

---

.github/dependabot.yml

This PR reschedules dependabot to monthly, as we don't have enough bandwidth to check this PRs that often, and it's not that beneficial to us either.

chore(common): schedule dependabot monthly

---

packages/field-plugin/src/createFieldPlugin/createFieldPlugin.ts
packages/field-plugin/src/createFieldPlugin/createPluginActions/createPluginMessageListener/handlePluginMessage.ts

This PR fixes the regression about postMessage target origin. We used to use `*`, but decided to be more explicit. However it's not `app.storyblok.com` but it was supposed to `plugins.storyblok.com`.

fix(lib): fix regression about postMessage target origin

---

packages/field-plugin/src/createFieldPlugin/createFieldPlugin.ts
packages/field-plugin/src/createFieldPlugin/createPluginActions/createPluginMessageListener/createPluginMessageListener.ts
packages/field-plugin/src/createFieldPlugin/createPluginActions/createPluginMessageListener/handlePluginMessage.ts
packages/field-plugin/src/messaging/pluginMessage/containerToPluginMessage/FieldPluginSchema.ts
packages/sandbox/src/components/TranslatableCheckbox.tsx

It makes the `translatable` property optional in the plugin's `schema`.
JIRA: EXT-2267
The `translatable` property is not always present and we were expecting it to be. 
So, for example, in the Field Plugin Editor (where this property doesn't exist in the schema), the field plugin was breaking because the schema validation just failed due to the lack of this property.

fix(lib): make the translatable property optional

---

eslint.config.js
packages/cli/templates/vue3/src/components/FieldPluginExample/index.vue

This PR fixes eslint warning by turning off some rules.
prettier [automatically applies self closing tag](https://stackoverflow.com/questions/65105287/how-to-stop-prettier-from-using-the-old-self-closing-tag-syntax) `<hr> → <hr />`, and it happens normally by VSCode's prettier extension (I guess we all are using it).
However, we had an eslint rule that is the opposite. So they're conflicting. While it's impossible to configure prettier to stop doing that, we can disable this single eslint rule. Of course, we can setup git pre-commit hook, so that it can run `eslint --fixed`, so even if prettier applied the self closing tag, the eslint would fix it before commit. But I think that's a bit too much. If we really need to have that rule, then we could setup the git pre-commit hook.

chore(common): fix eslint warning

---

packages/demo/vite.config.ts
scripts/prepare-dev-vite-configs.mjs

#407 moved `packages/field-plugin/helpers` to `packages/lib-helpers` and it broke `yarn dev:vue3`, `yarn dev:xxx` commands. This PR fixes the regression.

chore(common): fix scripts to run templates in dev

---

packages/cli/src/__tests__/main.test.ts
packages/cli/src/commands/deploy/helper.ts
packages/cli/src/commands/deploy/index.ts
packages/cli/src/main.ts

This PR adds a new flag to the deploy command for publishing a new version of field plugin during the update process.
As we have found out trough researching the APIs the POST request automatically publishes a field-plugin, therefore it is not possible to opt-out during the initial creations. However when using PUT method, updating the plugin, it is possible to send `publish` property, which will either only save the new plugin or save and publish it as a new version. 
Here are all the new test cases that are introduced by the change and are applied when a field plugin is updated. `
`yarn deploy --no-publish`
`yarn deploy --skipPrompts`
`yarn deploy --skipPrompts --no-publish`
#380
`yarn deploy`
--> NEW: User is prompted with the following question **Do you want to publish a new version …

feat(cli): on update process add flag to opt-out from publishing

---

packages/lib-helpers/react/src/useFieldPlugin.ts

In `@storyblok/field-plugin/react`, the effects are not being cleaned up, because the cleanup function is not returned from the `useEffect` callback.
I also don't see any cleanup in the Vue 3 helper, but I am not addressing this in this PR. (SHAPE-7195)
JIRA: SHAPE-7192
Effects must be cleaned up.
The demo app uses `@storyblok/field-plugin/react`:
1. Run `yarn workspace demo dev`
2. Open the sandbox https://plugin-sandbox.storyblok.com/field-plugin?url=http%3A%2F%2Flocalhost%3A8080%2F
The app should work normally. You don't normally notice the lack of cleanup, but in local development mode, you'd see the effects run at least twice, and possibly even more if you're modifying the helper itself.

fix(helper): effects are not cleaned up in @storyblok/field-plugin/react

---

packages/lib-helpers/vue3/src/useFieldPlugin.ts

In the vue3 helper, side effects from `createFieldPlugin` are not being cleaned up.
If the application is never remounted, this is normally not a problem.
The Vue3 template should work as before.

fix(helper): clean up side effects in Vue 3 helper

---

packages/cli/templates/js/src/main.js
packages/cli/templates/react/src/components/FieldPlugin.tsx
packages/cli/templates/react/src/components/FieldPluginExample/index.tsx
packages/cli/templates/vue2/src/fieldPlugin.js
packages/cli/templates/vue3/src/components/FieldPlugin.vue
packages/cli/templates/vue3/src/components/FieldPluginExample/index.vue
packages/demo/src/components/FieldPluginDemo.tsx
packages/field-plugin/src/createFieldPlugin/createFieldPlugin.ts
packages/field-plugin/src/createFieldPlugin/createPluginActions/createPluginActions.ts
packages/field-plugin/src/messaging/pluginMessage/pluginToContainerMessage/PluginLoadedMessage.test.ts
packages/field-plugin/src/messaging/pluginMessage/pluginToContainerMessage/PluginLoadedMessage.ts
packages/sandbox/src/components/FieldPluginSandbox.tsx
packages/sandbox/src/components/FieldTypePreview.tsx

There is an issue that makes various elements on the screen overlap the field plugin modal:
This happens because the field plugin is not using Teleport, but instead uses dynamic styling on its wrapping element to go from `position: relative` to `position: absolute`. But the iframe (and its wrapping div element) might very well not have the highest priority in its stacking context. The way this is normally solved in dialogs is to use `<Teleport>` to mount the element outside the stacking context, (somewhere next to the application root element).
However, this is not possible to implement without some kind of a breaking change: without the `Teleport`, the iframe element never remounts, which means that the plugin's application state is preserved between. transitions between modal and …

feat(sandbox,lib,demo): modal in portal

---

package.json
packages/cli/package.json
packages/field-plugin/package.json

Set licenses in the package.json files so that it appears on NPM

chore(common): set MIT license in package.json

---

.github/workflows/npm-publish-cli.yml
.github/workflows/npm-publish-library.yml

When you open a draft release, the workflow does not trigger. 
See https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#release

ci(common): publish to NPM when you publish a draft release

---

packages/field-plugin/src/createFieldPlugin/FieldPluginData.ts
packages/field-plugin/src/createFieldPlugin/createPluginActions/createPluginActions.test.ts
packages/field-plugin/src/createFieldPlugin/createPluginActions/createPluginMessageListener/handlePluginMessage.test.ts
packages/field-plugin/src/createFieldPlugin/createPluginActions/partialPluginStateFromStateChangeMessage.ts
packages/field-plugin/src/messaging/pluginMessage/containerToPluginMessage/LoadedMessage.test.ts
packages/field-plugin/src/messaging/pluginMessage/containerToPluginMessage/LoadedMessage.ts
packages/field-plugin/src/messaging/pluginMessage/containerToPluginMessage/StateChangedMessage.test.ts
packages/field-plugin/src/messaging/pluginMessage/containerToPluginMessage/StateChangedMessage.ts
packages/lib-helpers/test/src/index.ts
packages/sandbox/src/components/FieldPluginSandbox.tsx

This PR includes the userID to the data response retrieved on state change and loaded state from a field plugin as documented within our [Field plugin API documentation](https://www.storyblok.com/docs/plugins/plugin-storyblok-mixin)
JIRA: [SHAPE-7741](https://storyblok.atlassian.net/browse/SHAPE-7741)
To test, run the following commands below (on separate terminals):
- `yarn dev:lib`.
- `yarn dev:demo`.
- `yarn dev:sandbox`.
These commands above should get your sandbox, field-plugin demo, and field-plugin library setup and running successfully.
Copy your currently running local sandbox URL, `http://localhost:7070/,` and place it within the file `packages/field-plugin/src/createFieldPlugin/createFieldPlugin.ts`.
This facilitates communication between your sandbox and field plugin through …

fix(lib): include userid to data response from field plugin

---

packages/sandbox/src/components/FieldTypePreview.tsx

This PR adds the permissions to allow copy/paste functionality from Plugins through the IFRAME.
JIRA: [SHAPE-9838](https://storyblok.atlassian.net/browse/SHAPE-9838)
1. Navigate to `packages/demo/src/components/FieldPluginDemo.tsx` and replace its contents with:
```
export const FieldPluginDemo: FunctionComponent = () => {
return (
<div>
<button onClick={copyToClipboard}>
Copy to Clipboard
</button>
Read Clipboard Text: {copiedText}
<button onClick={readFromClipboard}>Read from Clipboard</button>
</div>
)
}
export const CopyToClipboard = () => {
const copyToClipboard = () => {
navigator.clipboard.writeText('Hello world').then(
() => {
console.log('Copying to clipboard was successful!')
},
(err) => {
console.error('Could not copy text: ', err)
},
)
}
return (
<button …
```

feat(sandbox): add copy and paste iframe permissions
